# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pAUC <- function(Truth, Pred, n) {
    .Call(`_LaCDS_pAUC`, Truth, Pred, n)
}

Max <- function(a, b) {
    .Call(`_LaCDS_Max`, a, b)
}

Update <- function(wker, gtau, t, X, ind, ker_t, beta_v, max_t, c, r, nker) {
    .Call(`_LaCDS_Update`, wker, gtau, t, X, ind, ker_t, beta_v, max_t, c, r, nker)
}

Like <- function(wker, gtau, t, X, ind, ker_t, beta_v, max_t, c, r) {
    .Call(`_LaCDS_Like`, wker, gtau, t, X, ind, ker_t, beta_v, max_t, c, r)
}

NW <- function(wker, gtau, t, X, ind, ker_t, beta_v, tol, max_iter, alpha) {
    .Call(`_LaCDS_NW`, wker, gtau, t, X, ind, ker_t, beta_v, tol, max_iter, alpha)
}

lik <- function(t, X, ind, Beta_t, Beta_v, pi, max_t, r, c, group) {
    .Call(`_LaCDS_lik`, t, X, ind, Beta_t, Beta_v, pi, max_t, r, c, group)
}

Inf2 <- function(wker, pi, tau, t, X, ind, Ker_t, Beta_v, max_t, c, r, group, nker) {
    .Call(`_LaCDS_Inf2`, wker, pi, tau, t, X, ind, Ker_t, Beta_v, max_t, c, r, group, nker)
}

EM <- function(wker, Z, group, t, X, ind, beta_t, beta_v, tol, tol2, max_iter, min_iter, alpha) {
    .Call(`_LaCDS_EM`, wker, Z, group, t, X, ind, beta_t, beta_v, tol, tol2, max_iter, min_iter, alpha)
}

